apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - proxy.yml

configMapGenerator:
  - name: ssh-key
    files:
      - id_rsa.pub
  - name: ssh-config
    files:
      - sshd_config
