apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spin
    cluster: spin-proxy
  name: spin-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spin
      cluster: spin-proxy
  template:
    metadata:
      labels:
        app: spin
        cluster: spin-proxy
    spec:
      containers:
      - image: linuxserver/openssh-server:8.3_p1-r0-ls25
        imagePullPolicy: IfNotPresent
        name: sshd
        env:
          - name: PUID
            value: "0"
          - name: PGID
            value: "0"
          - name: USER_NAME
            value: "spinnaker"
          - name: SUDO_ACCESS
            value: "true"
          - name: PUBLIC_KEY_FILE
            value: /keys/id_rsa.pub
        volumeMounts:
        - name: ssh-key
          mountPath: /keys
        - name: ssh-config
          mountPath: /config/ssh_host_keys/sshd_config
          subPath: sshd_config
      volumes:
      - name: ssh-key
        configMap:
          name: ssh-key
          defaultMode: 0600
      - name: ssh-config
        configMap:
          name: ssh-config
          defaultMode: 0600
---
apiVersion: v1
kind: Service
metadata:
  name: spin-proxy
spec:
  ports:
    - name: ssh
      port: 2222
      targetPort: 2222
      protocol: TCP
  selector:
    name: spin-proxy
